services:
  infra-postgres:
    ports:
      - "5432:5432"
  infra-kafka:
    deploy:
      resources:
        limits:
          cpus: "0.7"
    image: apache/kafka
    ports:
      - "9092:9092"
  infra-kafka2:
    deploy:
      resources:
        limits:
          cpus: "0.7"
    image: apache/kafka
    ports:
      - "9093:9092"
  infra-kafka3:
    deploy:
      resources:
        limits:
          cpus: "0.7"
    image: apache/kafka
    ports:
      - "9094:9092"
  infra-tofu:
    build:
      context: deploy/tofu
  infra-kafka-ui:
    ports:
      - "9000:8080"
  hub_submitter:
    build:
      context: internal
      dockerfile: services/hub_submitter_service/DockerfileDev
    volumes:
      #      for debug
      - ./internal/services/hub_submitter_service:/app/src/service:cached
      - ./internal/pkg:/app/pkg:cached
    ports:
      - "8056:8056"
      - "40000:40000"
volumes:
  postgres_data: