// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: common/base_event.proto

package base_event

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CorrelationInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageId     string                 `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	CorrelationId string                 `protobuf:"bytes,2,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CorrelationInfo) Reset() {
	*x = CorrelationInfo{}
	mi := &file_common_base_event_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CorrelationInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CorrelationInfo) ProtoMessage() {}

func (x *CorrelationInfo) ProtoReflect() protoreflect.Message {
	mi := &file_common_base_event_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CorrelationInfo.ProtoReflect.Descriptor instead.
func (*CorrelationInfo) Descriptor() ([]byte, []int) {
	return file_common_base_event_proto_rawDescGZIP(), []int{0}
}

func (x *CorrelationInfo) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *CorrelationInfo) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *CorrelationInfo) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type BaseEvent struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	CorrelationInfo *CorrelationInfo       `protobuf:"bytes,1,opt,name=correlation_info,json=correlationInfo,proto3" json:"correlation_info,omitempty"`
	Type            string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Payload         []byte                 `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *BaseEvent) Reset() {
	*x = BaseEvent{}
	mi := &file_common_base_event_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BaseEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BaseEvent) ProtoMessage() {}

func (x *BaseEvent) ProtoReflect() protoreflect.Message {
	mi := &file_common_base_event_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BaseEvent.ProtoReflect.Descriptor instead.
func (*BaseEvent) Descriptor() ([]byte, []int) {
	return file_common_base_event_proto_rawDescGZIP(), []int{1}
}

func (x *BaseEvent) GetCorrelationInfo() *CorrelationInfo {
	if x != nil {
		return x.CorrelationInfo
	}
	return nil
}

func (x *BaseEvent) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *BaseEvent) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

var File_common_base_event_proto protoreflect.FileDescriptor

const file_common_base_event_proto_rawDesc = "" +
	"\n" +
	"\x17common/base_event.proto\x12\x06common\x1a\x1fgoogle/protobuf/timestamp.proto\"\x92\x01\n" +
	"\x0fCorrelationInfo\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\tR\tmessageId\x12%\n" +
	"\x0ecorrelation_id\x18\x02 \x01(\tR\rcorrelationId\x129\n" +
	"\n" +
	"created_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"}\n" +
	"\tBaseEvent\x12B\n" +
	"\x10correlation_info\x18\x01 \x01(\v2\x17.common.CorrelationInfoR\x0fcorrelationInfo\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x18\n" +
	"\apayload\x18\x03 \x01(\fR\apayloadB\x0eZ\f.;base_eventb\x06proto3"

var (
	file_common_base_event_proto_rawDescOnce sync.Once
	file_common_base_event_proto_rawDescData []byte
)

func file_common_base_event_proto_rawDescGZIP() []byte {
	file_common_base_event_proto_rawDescOnce.Do(func() {
		file_common_base_event_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_common_base_event_proto_rawDesc), len(file_common_base_event_proto_rawDesc)))
	})
	return file_common_base_event_proto_rawDescData
}

var file_common_base_event_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_common_base_event_proto_goTypes = []any{
	(*CorrelationInfo)(nil),       // 0: common.CorrelationInfo
	(*BaseEvent)(nil),             // 1: common.BaseEvent
	(*timestamppb.Timestamp)(nil), // 2: google.protobuf.Timestamp
}
var file_common_base_event_proto_depIdxs = []int32{
	2, // 0: common.CorrelationInfo.created_at:type_name -> google.protobuf.Timestamp
	0, // 1: common.BaseEvent.correlation_info:type_name -> common.CorrelationInfo
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_common_base_event_proto_init() }
func file_common_base_event_proto_init() {
	if File_common_base_event_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_common_base_event_proto_rawDesc), len(file_common_base_event_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_common_base_event_proto_goTypes,
		DependencyIndexes: file_common_base_event_proto_depIdxs,
		MessageInfos:      file_common_base_event_proto_msgTypes,
	}.Build()
	File_common_base_event_proto = out.File
	file_common_base_event_proto_goTypes = nil
	file_common_base_event_proto_depIdxs = nil
}
